blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myblogapp.urls", namespace="blog")),
    path('summernote/', include('django_summernote.urls')),
    path('mdeditor/', include('mdeditor.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblogapp/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed
app_name = "blog"

urlpatterns = [
    
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    # path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>",
        views.post_detail,
        name="post_detail",
    ),
    # path("<int:post_id>/share/", views.post_share, name="post_share"),
    path('<int:post_id>/comment/',views.post_comment, name ='post_comment'),
    path("feed/", LatestPostFeed(), name="post_feed"),
    path("search/",views.post_search, name="post_search")
]

myblogapp/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager
from django_summernote.fields import SummernoteTextField
from mdeditor.fields import MDTextField

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_posts"
    )
    thumbnail = models.ImageField(upload_to='media/',default="/placeholder.svg")
    body = MDTextField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    object = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        on_delete = models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return 'Comment by {self.name} on {self.post}'
    

myblogapp/forms.py
from django import forms
from .models import Comment
from django_summernote.widgets import SummernoteWidget

class SearchForm(forms.Form):
    query = forms.CharField()

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    # email = forms.EmailField(required=False)
    # to = forms.EmailField(required=False)
    comments = forms.CharField(required=True, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    class Meta:
        model = Comment
        fields = ['name','email','body']
        widgets = {
            'body': SummernoteWidget()
        }

myblogapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post
from taggit.models import Tag
from .forms import EmailPostForm,CommentForm,SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.db.models import Count, Q

# Create your views here.

def post_search(request):
    form = SearchForm()
    query = None
    
    results = []

    if ('query' in request.GET):
        form = SearchForm(request.GET)
        if(form.is_valid()):
            query = form.cleaned_data['query']
            results = Post.published.filter(Q(title__icontains=query) | Q(body__icontains=query))
            
    return render(request,'blog/post/search.html',{'form': form,'query':query,'results': results})

def post_list(request, tag_slug = None):
    post_list = Post.published.all()
    tag = None
    if(tag_slug):
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    middle_page = (paginator.num_pages) // 2

    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    return render(request, "blog/post/list.html", {"posts": posts,'middle_page': middle_page})


def post_detail(request, post, year, month, day):
    post = get_object_or_404(
        Post,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        status=Post.Status.PUBLISHED,
    )

    comments = post.comments.filter(active=True)
    form = CommentForm()

    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    return render(request, "blog/post/detail.html", {"post": post,'comments': comments,'form':form,'similar_posts':similar_posts})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id = post_id, status=Post.Status.PUBLISHED)
    comment = None

    comments = post.comments.filter(active=True)
    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    form = CommentForm(data=request.POST)
    if(form.is_valid()):
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(request,'blog/post/detail.html',{'post': post,'form':form,'comments':comments,'similar_posts':similar_posts})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"


# def post_share(request, post_id):

#     post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
#     sent = False
#     if request.method == "POST":

#         form = EmailPostForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             post_url = request.build_absolute_uri(post.get_absolute_url())
#             subject = (
#                 f"{cd['name']} ({cd['email']})" f"recomends you to read {post.title}"
#             )
#             message = (
#                 f"Read { post.title} at {post_url}\n\n"
#                 f"{cd['name']}'s comments: {cd['comments']}"
#             )
#             send_mail(
#                 subject=subject,
#                 message=message,
#                 from_email=None,
#                 recipient_list=[cd["to"]],
#             )
#             sent = True
#     else:
#         form = EmailPostForm()

#     return render(request, "blog/post/share.html", {"post": post, "form": form})

myblogapp/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="pt">
  <head>
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="author" content="Matheus Santos Evangelista">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="HTML, CSS, JavaScript, Django, Blog">
    <meta name="description" content="Meu blog pessoal">
  <link href="{% static "css/blog.css" %}" type='text/css' rel="stylesheet">

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
    {% block extra_css %}
      {{ form.media.css }}
    {% endblock %}
  </head>
  <body>
    <div class="navigation">
      <input type="checkbox" class="navigation__checkbox" id="nav-toggle">
      <label for="nav-toggle" class="navigation__button">
        <span class="navigation__icon" aria-label="toggle navigation menu"></span>
      </label>
      <div class="navigation__background"></div>

      <nav class="navigation__nav" role="navigation">
        <ul class="navigation__list">
          <li class="navigation__item">
            <a href="http://www.localhost:8000/" class="navigation__link"><span>01</span>Lista Posts</a>
          </li>
          <li class="navigation__item">
            <a href="https://matheusevangelista.vercel.app/sobre" class="navigation__link"><span>02</span>Sobre</a>
          </li>
          <li class="navigation__item">
            <a href="https://matheusevangelista.vercel.app/projetos" class="navigation__link"><span>03</span>Projetos</a>
          </li>
          <li class="navigation__item">
            <a href="https://matheusevangelista.vercel.app/contatos" class="navigation__link"><span>04</span>Contatos</a>
          </li>
          </li>
    </ul>
  </nav>
</div>
<div class="main">
    <div id="content">{% block content %} {% endblock content %}</div>
    
  
    <div id="sidebar">
      <h2 class="sidebar-title" >Meu Blog</h2>
      <p class="sidebar-about"> Esse é o meu blog pessoal seja bem vindo! Eu escrevi um total de <span class="numposts">{% total_posts %}</span> posts até agora</p>
     
    <div class="form-feed-wrapper">
      <form name="search" id="searchform" action="{% url 'blog:post_search' %}" method="get" class="form-wrapper">
        <input type="text" id="query" name="query" placeholder="Pesquisar por..." required>
    
          <button class="submitsearch" type="submit" form="searchform" value="Submit">Pots</button>
     
      </form>


            <a href="{% url "blog:post_feed" %}">
            <div class="css-art css-art-rss">
              <div class="css-art-rss-inner-1">
                <div class="css-art-rss-inner-2">
                  <div class="hide-text">RSS Feed</div>
                </div>
              </div>
            </div>
          </a>
  </div>
      <div class="sidebar-lastposts">
        <h3 class="sidebar-lastpostsHeader">Ultimos posts</h3>
        <div class="sidebar-list-lastposts">
          {% comment %} {% show_latest_posts 3 %} {% endcomment %}
          {% show_latest_posts 5 as latest_posts %}
{% for post in latest_posts %}
<a class="links" href="{{post.get_absolute_url}}">
    {{ post.title|truncatewords:5}}
</a>
<br>
 {% endfor %}

        </div>
      </div>
      <div class="sidebar-lastcommentscontainer">
        <h3 class="sidebar-lastcomments">Posts mais comentados</h3>
        {% get_most_commented_posts as most_commented_posts %}
        
          {% for post in most_commented_posts %}
            <a class="links" href="{{ post.get_absolute_url }}">{{ post.title | truncatewords:5}}</a>
            <br>
          {% endfor %}
        </ul>
    </div>
    <div class="sidebar-tagscontainer">
      <h3>Todas as Tags</h3>
  
        {% get_all_tags as all_tags %}
        {% for tag in all_tags %}
        <a class="links" href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name}} 
        </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </ul>
    
    </div>
    <script src="{% static 'js/blog.js' %}"></script>

    </div> 
  
    <button id="backToTopBtn" onclick="scrollToTop()">Back to Top</button>
   
  </div>
  </div>
  {% block extra_js %}
  {{ form.media.js }}
{% endblock %}
  </body>
</html>

myblogapp/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Comentarios {% endblock title %}

{% block content %}
    {%if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}"> Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

myblogapp/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock title %}

{% block content %}
  <div class="backarrow">
      <a href="/">
          <svg class="arrowsvg" viewBox="0 0 18 17" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g id="prev" transform="translate(8.500000, 8.500000) scale(-1, 1) translate(-8.500000, -8.500000)">
                <polygon class="arrow" points="16.3746667 8.33860465 7.76133333 15.3067621 6.904 14.3175671 14.2906667 8.34246869 6.908 2.42790698 7.76 1.43613596"></polygon>
                <polygon class="arrow-fixed" points="16.3746667 8.33860465 7.76133333 15.3067621 6.904 14.3175671 14.2906667 8.34246869 6.908 2.42790698 7.76 1.43613596"></polygon>
                <path d="M-1.48029737e-15,0.56157424 L-1.48029737e-15,16.1929159 L9.708,8.33860465 L-2.66453526e-15,0.56157424 L-1.48029737e-15,0.56157424 Z M1.33333333,3.30246869 L7.62533333,8.34246869 L1.33333333,13.4327013 L1.33333333,3.30246869 L1.33333333,3.30246869 Z"></path>
            </g>
          </svg>
      </a>
  </div>

<div class="detail">
    <a class="detail-title" href="/">{{ post.title }}</a>
    <p class="date">
      Publicado {{ post.publish }}
    </p>
    <div class="imagedetail">
    <img class="detailfigure" src="{{ post.thumbnail.url }}" alt="{{ post.title }}">
    </div>
    <div class="reveal">
      <div class="mousewrapper">
        <div class="boxmouse">
        <div class="mouse">
          <span style="--i: 1"></span>
          <span style="--i: 2"></span>
          <span style="--i: 3"></span>
        </div>
      </div>
      
      <h3 class="headerscroll">Rode para baixo</h3>
    </div>
  </div>
    <hr class="divider">
    <div class="reveal">
       
      {% for line in post.body.splitlines %}
        {{ line|safe|markdown }}
      {% endfor %}
  </div>

<hr class="divider">
<h3 class="tags">
tags::
    {% for tag in post.tags.all %}
              <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
          
    {% endfor %} 
</h3>
  </div>
   
    {% comment %} <div class="similar-posts">
      <h2>Similar posts</h2>
      <ul>

      {% for post in similar_posts %}
        <li>
        <a class="similar-link" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
     {% empty %}
          <div>
            Não existem nenhum posts similar
          </div>

  {% endfor %}
        </ul>
</div> {% endcomment %}

      <div class="commentcontainer">
      {% with comment.count as total_comments %}
        <h2>
          {{ total_comments }} Comentario{{total_comments|pluralize}}
        </h2>
      {% endwith %}
      {% for comment in comments %}
    <div class="comments">
    <p class="info">
            Comentario {{ forloop.counter }} por {{ comment.name }}
         </p>

         {{ comment.body|markdown }}
        </div>
        {% empty %}
        <p> Esse post nao possui comentarios
    {% endfor %}
    <div class="insertComment">
    {% include "blog/post/includes/comment_form.html" %}
    </div>
  </div>
{% endblock content %}

myblogapp/templates/blog/post/includes/comment_form.html
<h2>Adicione um novo comentario</h2>

<form action="{%url "blog:post_comment" post.id%}" class="comment-form" method="post">
    {{ form.as_p | safe}}

    {% csrf_token %}
    <p><input type="submit" value="adicionar comentario"></p>
</form>

myblogapp/templates/blog/post/includes/pagination.html
<ul class="pagination">
    {% if page.has_previous %}
        <li>
            <a class="previouscontainer" href="?page={{ page.previous_page_number }}">
                Anterior
            </a>
        </li>
    {% endif %}
    
    {% comment %} <li class="current"> {% endcomment %}
        {% comment %} Page {{ page.number }} of {{ page.paginator.num_pages }}. {% endcomment %}
    {% comment %} </li> {% endcomment %}
 
    {% for pagenumber in page.paginator.page_range %}
        <li>
            <a href="?page={{ pagenumber }}" class="{% if pagenumber == page.number %}active{% endif %}">
                {{ pagenumber }}
            </a>
        </li>
    {% endfor %}

    {% if page.has_next %}
        <li>
            <a class="nextcontainer" href="?page={{ page.next_page_number }}">
                Proximo
            </a>
        </li>
    {% endif %}

</ul>
<div class="paginationtext">
    Pagina {{ page.number }} de {{ page.paginator.num_pages }}
</div>

myblogapp/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

myblogapp/templates/blog/post/list.html
{% extends "blog/base.html" %} 
{% load blog_tags %}
{% load static %}

{% block title %}Home{% endblock title %}
{% block content %}
<div class="postlist">
    <div class="postHeader">
        <h1>Matheus Evangelista</h1>
        <p>🇧🇷 • <small>Desenvolvedor  </small> </p>
        <h3>Areas de interesse</h3>
        <small class="interesse">dev web, mobile, python, java</small>
    </div>
        <div class="posts">
        <h1><a class="listPostsHeader" href="/">Meus posts</a></h1>
        
        {% for post in posts %}
        <a href="{{ post.get_absolute_url }}">
                    
            <div class="post">
                    <p class="post-title"> {{ post.title }} </p>

                        <p class="date">Publicado {{ post.publish }}</p>
                    <img class="postFigure" src="{{ post.thumbnail.url }}" alt="Imagem do post"/>
                    {% comment %} {{ post.body |markdown| truncatewords_html:10 }} {% endcomment %}
                    
            </div>
        </a>
            
        {% endfor %}
        </div>
 
    {% include "blog/post/includes/pagination.html" with page=posts %}
    </div>
      {% comment %} <button class="scrollToTopBtn">☝️</button> {% endcomment %}
{% endblock content %}

myblogapp/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Resultados da Pesquisa{% endblock title %}
{% block content %}

<div class="backarrow">
    <a href="/">
        <svg class="arrowsvg" viewBox="0 0 18 17" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="prev" transform="translate(8.500000, 8.500000) scale(-1, 1) translate(-8.500000, -8.500000)">
              <polygon class="arrow" points="16.3746667 8.33860465 7.76133333 15.3067621 6.904 14.3175671 14.2906667 8.34246869 6.908 2.42790698 7.76 1.43613596"></polygon>
              <polygon class="arrow-fixed" points="16.3746667 8.33860465 7.76133333 15.3067621 6.904 14.3175671 14.2906667 8.34246869 6.908 2.42790698 7.76 1.43613596"></polygon>
              <path d="M-1.48029737e-15,0.56157424 L-1.48029737e-15,16.1929159 L9.708,8.33860465 L-2.66453526e-15,0.56157424 L-1.48029737e-15,0.56157424 Z M1.33333333,3.30246869 L7.62533333,8.34246869 L1.33333333,13.4327013 L1.33333333,3.30246869 L1.33333333,3.30246869 Z"></path>
          </g>
        </svg>
    </a>
</div>
<div class="search">
    <h1>Resultados da Pesquisa para "{{ query }}"</h1>

    {% if results %}
        <ul>
            {% for post in results %}
            <a href="{{ post.get_absolute_url }}">
                <li class="post">
                    <p class="post-title">{{ post.title }}</p>
                    <p>Publicado em {{ post.publish }}</p>
                </li>
            </a>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nenhum resultado encontrado.</p>
    {% endif %}
</div>
{% endblock content %}

myblogapp/templates/blog/post/share.html
{%extends "blog/base.html" %}

{% block title %}Compartilhe posts {% endblock title %}

{%block content %}
    {% if sent %}
        <h1> Email enviado com sucesso </h1>
        <p>
            "{{ post.title }}" foi enviado com sucesso para: {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Compartilhe "{{ post.title }}" por e-mail </h1>

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
                <input type="submit" value="Send Email">

        </form>
    {% endif %}
{% endblock %}